server:
  port: 7065

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mpw:+P1P94v+pwQqx9yNoH0CrinbOWpI/bKjuAfUOXVKpvwJLKQby/XMGl3In0tX8XMF57t0k7iX2dXGMXZDnLm411DmoiDriUkO90jkrarlqEackphFwbVzIuJe4dYtrS8kFnR/BBTH0gHZMw0n/k2dgwUxXvrz+MZu28CuBp3UiAFfvyLzYWCAb4OTyt11zISyd+4Yxx1koYXIpDAmj8qaGg==
    password: mpw:gTUL78Wt5noB6vk3c7GvGg==
    username: mpw:5c5rzOtCn5+UTZLn+rwRlg==

  # 配置plus
  mybatis-plus:
    #配置mybatis-plus xml 路径
    mapper-locations: classpath:/mapper/**/*Mapper.xml
    #实体类别名, 多个package用[ , 或 ; ]区分
    typeAliasesPackage: com.starda.managesystem.mapper
    global-config:
      db-config:
        logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.starda.managesystem.pojo.enums
    configuration:
      #配置驼峰命名规则
      map-underscore-to-camel-case: true
      cache-enabled: false