server:
  port: 7065
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
    basedir: /home/tmp

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.110.80:3306/manage_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2b8
    password: Qiudaye90900..
    username: root

#文件大小
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 32MB

  # 配置plus
  mybatis-plus:
    #配置mybatis-plus xml 路径
    mapper-locations: classpath:/mapper/**/*Mapper.xml
    #实体类别名, 多个package用[ , 或 ; ]区分
    typeAliasesPackage: com.starda.managesystem.mapper
    global-config:
      db-config:
        logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.starda.managesystem.pojo.enums
    configuration:
      #配置驼峰命名规则
      map-underscore-to-camel-case: true
      cache-enabled: false

#输出日志
logging:
  config: classpath:log4j2.xml
  level:
    com.starda.managesystem: trace